---
title: "STAT 446 - Final Project Report Code"
author: "Harley Clifton & Mark Braun"
date: "December 8, 2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lattice)
library(survey)
source("confintt.R")
```

## Stratified SRS Regression Analysis 

```{r}
# Data set up

nitrogen  <- c(26.2,20.1,22.7,23.3,17.1,16.8,16.1,16.5,16.8,19.8,15.8,15.1,16.1,17.0,
     13.3,23.9,13.9,12.4,20.8,23.3,18.0, 9.8,13.5,15.8,20.6,21.5,10.8,13.4,20.6,
     18.4,20.4, 8.5, 4.5, 5.4,18.1, 9.1,11.0, 7.0, 7.0,11.0,17.0, 7.1, 8.1, 2.8,
     19.4,17.5,15.8,16.2, 6.7,14.3,19.9,13.6, 9.2,21.5,10.2,21.1,11.0,21.9,23.3,
     20.6,23.6,22.4,19.7,17.9,15.2,17.7,15.6,11.2,14.9,16.3,17.0,13.5, 9.0, 9.5,
     10.0, 6.7,15.5, 6.7,17.1, 6.3,14.0, 1.4,17.1,14.1,14.3, 7.6,10.8,10.0,19.3,
     14.4,16.4,20.6,19.1,15.8,20.0,20.6,24.1,24.8,26.2,19.4,10.8, 6.4, 2.2,20.6,
     15.0, 9.8,10.8,11.4,15.6,11.2,12.8,13.6,14.4,15.3,14.8,18.4,16.1,14.3,15.2,
     18.9,16.3,17.9,18.9,20.2,22.0,22.0,20.4,19.7,19.9,17.1,19.4,20.6,23.0,22.0)

count <- c(141, 84,105,110, 59, 56, 56, 54, 60, 79, 50, 46, 55, 59,
         36,114, 40, 32, 89,112, 65, 21, 38, 52, 88, 94, 24, 37, 88,
         70, 85, 19,  5,  7, 67, 16, 27, 12, 11, 24, 60, 11, 15,  2,
         75, 61, 53, 52, 10, 42, 81, 40, 17, 93, 23, 90, 24, 96,111,
         89,114,101, 78, 65, 46, 63, 50, 27, 46, 53, 60, 38, 16, 20,
         22,  9, 51, 13, 61,  9, 43,  2, 59, 41, 42, 17, 24, 21, 78,
         42, 55, 86, 75, 52, 83, 88,116,127,139, 78, 27, 13,  5, 90,
         49, 23, 26, 30, 53, 29, 38, 44, 45, 52, 48, 72, 55, 45, 49,
         75, 58, 68, 75, 88,103, 99, 87, 81, 85, 64, 79, 92,111,100)

severity <- c(rep(1,62),rep(2,37),rep(3,28),rep(4,7))

dataset <- data.frame(count, nitrogen, severity)
severity1 <- subset(dataset, severity == 1)
severity2 <- subset(dataset, severity == 2)
severity3 <- subset(dataset, severity == 3)
severity4 <- subset(dataset, severity == 4)
```

```{r}
# Stratified Regression Estimation -- Separate Regression Estimator

# Each group in a separate plot
  xyplot(count ~ nitrogen | severity, cex=1.25,pch=19,
                 xlim=c(0,max(nitrogen)+10),ylim=c(0,max(count)+10))
  
# All groups in one plot, different colors for each group
  xyplot(count ~ nitrogen, groups=severity,cex=1.25,pch=19,
                xlim=c(0,max(nitrogen))+10, ylim=c(0,max(count)+10))

```

## Finding Estimates of the Mean and Standard Error for Each Stratum

```{r}
# Stratified Regression Estimation -- Separate Regression Estimator

# Stratum 1 data 
mux = mean(severity1$nitrogen)    # if population tx or xbar.U are unknown
n <- length(severity1)

counts1 <- severity1$count
nitro1 <- severity1$nitrogen

regdata <- data.frame(counts1,nitro1)
regdsgn <- svydesign(id=~1,data=regdata)
regdsgn

svyreg <- svyglm(counts1~nitro1,design=regdsgn)
svyreg
atmean <- c(1,mux)

# Plot the data with a fitted regression line
plot(nitro1,counts1,type="n", main="Count vs Nitrogen")
points(nitro1,counts1, pch=16)
abline(svyreg)

# Assign names to each model term
names(atmean) <- c("(Intercept)","nitro1")
atmean <- as.data.frame(t(atmean))

# Estimate the population mean
meanwgt <- predict(svyreg,newdata=atmean,total=1)
meanwgt

```

```{r}
# Stratum 2 data 
mux = mean(severity2$nitrogen)    # if population tx or xbar.U are unknown
n <- length(severity2)

counts2 <- severity2$count
nitro2 <- severity2$nitrogen

regdata <- data.frame(counts2,nitro2)
regdsgn <- svydesign(id=~1,data=regdata)
regdsgn

svyreg <- svyglm(counts2~nitro2,design=regdsgn)
svyreg
atmean <- c(1,mux)

# Plot the data with a fitted regression line
plot(nitro2,counts2,type="n", main="Count vs Nitrogen")
points(nitro2,counts2, pch=16)
abline(svyreg)

# Assign names to each model term
names(atmean) <- c("(Intercept)","nitro2")
atmean <- as.data.frame(t(atmean))

# Estimate the population mean
meanwgt <- predict(svyreg,newdata=atmean,total=1)
meanwgt

```

```{r}
# Stratum 3 data 
mux = mean(severity3$nitrogen)    # if population tx or xbar.U are unknown
n <- length(severity3)

counts3 <- severity3$count
nitro3 <- severity3$nitrogen

regdata <- data.frame(counts3,nitro3)
regdsgn <- svydesign(id=~1,data=regdata)
regdsgn

svyreg <- svyglm(counts3~nitro3,design=regdsgn)
svyreg
atmean <- c(1,mux)

# Plot the data with a fitted regression line
plot(nitro3,counts3,type="n", main="Count vs Nitrogen")
points(nitro3,counts3, pch=16)
abline(svyreg)

# Assign names to each model term
names(atmean) <- c("(Intercept)","nitro3")
atmean <- as.data.frame(t(atmean))

# Estimate the population mean
meanwgt <- predict(svyreg,newdata=atmean,total=1)
meanwgt


```
```{r}
# Stratum 4 data 
mux = mean(severity4$nitrogen)    # if population tx or xbar.U are unknown
n <- length(severity4)

counts4 <- severity4$count
nitro4 <- severity4$nitrogen

regdata <- data.frame(counts4,nitro4)
regdsgn <- svydesign(id=~1,data=regdata)
regdsgn

svyreg <- svyglm(counts4~nitro4,design=regdsgn)
svyreg
atmean <- c(1,mux)

# Plot the data with a fitted regression line
plot(nitro4,counts4,type="n", main="Count vs Nitrogen")
points(nitro4,counts4, pch=16)
abline(svyreg)

# Assign names to each model term
names(atmean) <- c("(Intercept)","nitro4")
atmean <- as.data.frame(t(atmean))

# Estimate the population mean
meanwgt <- predict(svyreg,newdata=atmean,total=1)
meanwgt

```



```{r}
############
# Stop here. Enter standard error from meanwgt and run rest of code.
############

  se.meanwgt = 0.8744962  # Stratum 1
  se.meanwgt = 1.367585   # Stratum 2
  se.meanwgt = 1.162522   # Stratum 3
  se.meanwgt = 0.6481052  # Stratum 4

# Estimate the population total 
that.reg <- 1600*meanwgt[1]
that.vec <- c(that.reg,1600*se.meanwgt) 
names(that.vec) <- c("Total Est","Std Error")
that.vec

# Estimate the population mean
meanhat.vec <- that.vec/1600
names(meanhat.vec) <- c("Mean Est","Std Error")
meanhat.vec
```


```{r}
citation(package = "survey")
citation(package = "lattice")
citation(package = "ggplot2")
```




```{r}
# Stratified separate regression estimation

 H <- 4                    # number of strata
Nh <- c(766,457,321,56)        # stratum sizes
nh <- c(62,37,28,7)             # stratum sample sizes 


CI.level = .95      # confidence level

# Enter vectors for stratum total estimates (stratum.est)
# and their standard errors (stratum.se)

  stratum.est <- c(43822.61, 23677.54, 17471.57,  4896.00)
  stratum.se  <- c(669.86411, 624.98624, 373.16949,  36.29389)

### Do not change any of the following code ### 
    df <- sum(nh)- H
     N <- sum(Nh)
     
# Estimate of the population total
  total.est <-  sum(stratum.est)
# Calculate standard error of population total estimate
  se.total.est <- sqrt(sum(stratum.se)^2)
  est.total.vec <- c(total.est,se.total.est)
  names(est.total.vec) <- c("Total Est.","Std Error") 
# Determine confidence interval for population total
  tstar = -qt((1-CI.level)/2,df)
  CI.total <- total.est + c(-1,1)*tstar*se.total.est
  est.total.vec
  CI.total 

# Estimate of the population mean
  mean.est <- total.est/N
# Calculate standard error of population mean estimate
  se.mean.est <- se.total.est/N
  est.mean.vec <- c(mean.est,se.mean.est)
  names(est.mean.vec) <- c("Mean Est.","Std Error")
# Determine confidence interval for population mean
  CI.mean <- CI.total/N
  est.mean.vec
  CI.mean

```

